### ISSUE TITLE
Kamon Play 2.6 for Scala 2.12

### ISSUE THREAD

**Issue by JeroenMinnaert** [kamon-io/kamon-play#11]
Hey guys, great work on merging in the Play 2.6 PR. Any idea when we can expect a build for 2.12?

**Comment by dpsoft** [comment]
@JeroenMinnaert on  the weekend ;)

**Comment by JeroenMinnaert** [comment]
@dpsoft ok thanks! :)

**Comment by JeroenMinnaert** [comment]
Bump

**Comment by JeroenMinnaert** [comment]
I hope you can find some time this weekend @dpsoft. We would really welcome this library being compiled for 2.12 so we can make our move to Play 2.6 :)

**Comment by dpsoft** [comment]
@JeroenMinnaert sorry for the late response, I just published the `0.6.8` version that includes `scala 2.12 support`

**Comment by JeroenMinnaert** [comment]
Thanks a lot @dpsoft!
