### ISSUE TITLE
Support netty server

### ISSUE THREAD

**Issue by jsw** [kamon-io/kamon-play#18]
Any plan to add support for the netty server? Our team has at least one play 2.6 service using netty because of an issue with the akka server. 

Would it be possible to move the play instrumentation to a section of code that is independent of which server is used?

**Comment by ivantopo** [comment]
Adding support for the Netty server is doable, maybe even copy-pasting it from the play 2.5 would work. Will check with @dpsoft about having a unified instrumentation point.

**Comment by chtefi** [comment]
Hey @dpsoft !

Sure. I did the PR #19, cleaned up some deprecated stuff in the handler. Note that I didn't test myself the thing in a real app. (I didn't PR from Powerspace, the code was slightly adapted for our needs).

**Comment by dpsoft** [comment]
@chtefi awesome!!. We take a look  asap. Thanks!!

**Comment by jsw** [comment]
I think this can be closed now. Reopen if I'm mistaken. Thanks all for the work on this!
