### ISSUE TITLE
Should the play dependencies be provided scope?

### ISSUE THREAD

**Issue by jsw** [kamon-io/kamon-play#23]
If user is using previous version of play, they will perhaps unexpectedly be upgraded to newer version of play by using this module, unless they include an explicit `dependencyOverride`. I think users want to be fairly conscientious about setting the play version.

I notice that `akkaHttp` and `typesafeConfig` are set to provided, so curious what the reasoning is.

**Comment by ivantopo** [comment]
To be honest, there wasn't any explicit policy on whether the frameworks' versions should be `provided` or `compile` dependencies. On one hand, given that the instrumentation is tied to private interfaces that might change between minor versions it might be good to have the dependency as `compile` and that will at least upgrade the classpath to the expected version. This fails short when the user has a potentially incompatible higher version and the module just wont work and we can't pull it down.

That's in theory, though. In practice we haven't seen instrumentation-breaking changes in minor releases so far (except from Akka).. in the particular case of Play I think it would be just fine to have the dependency as provided, that might even become a policy for the rest of the modules!

**Comment by jsw** [comment]
Makes sense. I don't have a strong opinion, just a single data point that it took me a while to notice that my play 2.6.9 app had play 2.6.10 dependencies (not all, some are still 2.6.9, which is possibly an awkward untested state to be in). If you choose to change to `provided`, maybe you just need documentation that indicates the known supported versions.
