### ISSUE TITLE
Changing operation="unknown-operation" dimension for incoming calls

### ISSUE THREAD

**Issue by pocman** [kamon-io/kamon-play#45]
Hi, 
here is the a subset of the metrics I get when using the following dependencies
```
"io.kamon" %% "kamon-core" % "1.1.4",
"io.kamon" %% "kamon-play-2.6" % "1.1.1",
"io.kamon" %% "kamon-prometheus" % "1.1.1"
```

```
span_processing_time_seconds_bucket{le="0.005",http_method="GET",operation="unknown-operation",error="false",span_kind="server",component="play.server.akka-http"} 4.0
span_processing_time_seconds_bucket{le="0.005",http_method="GET",operation="localhost:7780",parentOperation="unknown-operation",error="false",span_kind="client",component="play.client.ws"} 0.0
```

Is it possible to have some different from `operation="unknown-operation"` dimension for each route exposed by my akka http server ? 
This line https://github.com/kamon-io/kamon-play/blob/master/kamon-play-2.6.x/src/main/scala/kamon/play/instrumentation/RequestHandlerInstrumentation.scala#L45 would make me say that it's not possible.

Thanks for you help.

**Comment by dpsoft** [comment]
Hey Thomas,

Kamon should resolve a name of operation through:
https://github.com/kamon-io/kamon-play/blob/master/kamon-play-2.6.x/src/main/scala/kamon/play/OperationNameFilter.scala#L29,
also you can change the operation name using this:
https://github.com/kamon-io/kamon-play/blob/master/kamon-play-2.6.x/src/main/scala/kamon/play/action/TracingActions.scala

Cheers,

Diego.

**Comment by pocman** [comment]
Thansk, it's working great !
