### ISSUE TITLE
Kamon.reconfigure() fails loading classes when run in DEV mode

### ISSUE THREAD

**Issue by cspinetta** [kamon-io/kamon-play#50]
### Context:
I'm instrumenting a `Play` app with `Kamon 2.x`.
When running in `DEV` mode it has to call `Kamon.reconfigure()` in order to load the `application.conf` of the app.

##### Relevant content of the `application.conf`:
```scala
kamon {
  propagation.http {
    default {
      entries {
        incoming {
          custom-headers = "support.kamon.HeadersPropagation"
        }
        outgoing {
          custom-headers = "support.kamon.HeadersPropagation"
        }
      }
    }
  }
  instrumentation.logback {
    mdc.copy.enabled = true
    mdc.copy.tags = true
  }
}
```

### Problem
It fails when trying to load the class `support.kamon.HeadersPropagation`.

*The problem only happens when it runs on DEV mode.*

Evidence:
![Screenshot from 2019-07-11 22-14-22](https://user-images.githubusercontent.com/3776757/61097128-6916d400-a430-11e9-82f6-f0c4fdd25eea.png)

### Repo with example
Repo: https://github.com/cspinetta/kamon-on-play-27/tree/failure-on-reconfigure
* I'm working on this repo, so the `master` branch might not reproduce the problem. I created the branch `failure-on-reconfigure` for tracking this issue.
* Class `KamonModules` is who calls `Kamon.reconfigure()`.

### Setup
* Play: `2.7`.
* kamon-bundle: `2.0.0-RC3`.
* Kanela: `1.0.0-RC2`.

**Comment by ivantopo** [comment]
Hey @cspinetta, this is not really a problem with Kamon but rather with how Play organizes ClassLoaders in development mode, where Kamon ends up being loaded from a ClassLoader that cannot see your project classes.

That being said, you can probably hack this by calling `Kamon.changeClassLoader(...)` [see here](https://github.com/kamon-io/Kamon/blob/master/kamon-core/src/main/scala/kamon/ClassLoading.scala#L42-L45) from a custom Play application loader, then Kamon will always use that one when creating stuff. If you end up giving it a try please let me know!
