### ISSUE TITLE
Upload v2.0.0 to maven central

### ISSUE THREAD

**Issue by lglossman** [kamon-io/kamon-play#54]

**Comment by ivantopo** [comment]
Hey @lglossman, the 2.0 releases are in [Maven Central](https://search.maven.org/search?q=kamon-play):

![image](https://user-images.githubusercontent.com/1302854/62529980-fd156900-b83f-11e9-891a-81f3da38382a.png)

Please not that the version suffix is no longer needed, though. If you were using `kamon-play-2.7` on the 1.x versions that should now be just `kamon-play`, which works for Play 2.6 and Play 2.7.
