### ISSUE TITLE
Dead url in github header

### ISSUE THREAD

**Issue by MarcinAman** [kamon-io/kamon-play#57]
[Url](https://kamon.io/integrations/web-and-http-toolkits/play) in github header seems to be dead. Right now it goes to 404 nginx error page.

![image](https://user-images.githubusercontent.com/15652452/65384649-fb86fe00-dd24-11e9-9a37-298fc3d2a9aa.png)

**Comment by ivantopo** [comment]
Thanks @MarcinAman, fixed it!
