### ISSUE TITLE
new GuiceModule enforces you to use the Kamon object

### ISSUE THREAD

**Issue by an-tex** [kamon-io/kamon-play#7]
Before https://github.com/kamon-io/kamon-play/pull/2 you could inject KamonModule into a controller and call .metrics on it to create metrics, being sure kamon has already been started. 

The new GuiceModule doesn't expose anything, so it seems it's not meant to be injected at all and you should use the Kamon object again. But using it in the constructor if a Controller doesn't make sure Kamon is already started. So e.g. gauges are not properly initialized.

```
@Singleton
class SomeController @Inject()(/* some injections */) extends Controller {
  // is initialized before Kamon.start is called from GuiceModule
  Kamon.metrics.gauge("active", 1.second)(new CurrentValueCollector {
    def currentValue = {
       // is never called
       Logger.info("called");
       1
    }
  })
```

As a workaround one can inject GuiceModule into the controller to make sure Kamon is started, but this looks odd as you can't do anything with it and still need to use the Kamon object...

```
@Singleton
class SomeController @Inject()(kamon: KamonLoader) extends Controller {
   // is called after Kamon.start
  Kamon.metrics.gauge("active", 1.second)(new CurrentValueCollector {
    def currentValue = {
        // called every second as expected
       Logger.info("called");
       1
    }
  })
```

But with this workaround the Controller is pretty hard to test as it's tricky to create KamonLoader (not a trait) for a TestCase not having a started Application

**Comment by an-tex** [comment]
@ivantopo or am I using it wrong?

**Comment by ivantopo** [comment]
> The new GuiceModule doesn't expose anything, so it seems it's not meant to be injected at all and you should use the Kamon object again.

That's exactly as it should be! The new Guice module is loaded eagerly and taking the right configuration from the play environment, so, there shouldn't be any problem with initialization order and no need to inject Kamon anywhere, just use the Kamon object and that's it! 

If you run into any initialization problems just let us know, thanks for asking!

**Comment by an-tex** [comment]
I've described an initialization problem ;) Anything unclear in the example?

**Comment by ivantopo** [comment]
oh, sorry! so, the new module works fine when the application is running but then you are having issues just for the case of running tests?

**Comment by an-tex** [comment]
I'm having issues with a deployed and running application. When I use the Kamon object directly in the Controller initialisation, this code is called before the eagerly loaded Kamon Module is calling Kamon.start(). This means e.g. the gauge is not collecting any metrics. If I inject the KamonLoader into the controller (so the DI makes sure it is initialised before the Controller), everything works as expected again.

**Comment by ivantopo** [comment]
sorry for the stupid question, is this happening with version 0.6.6?

**Comment by an-tex** [comment]
Yep exactly. It seems the issue also happens in eagerly initialized Akka Actors with Kamon object usage directly in the class, but I haven't investigated this deeper to be sure. Just the metrics are missing of some actors since the update (Was fine with the injected Kamon). 

Maybe there's no precedence of eager Modules over Controllers/Actors in Guice? Then the order of initialisation might be just random. 

TBH I thought the previous solution with injecting a Kamon trait was the better way to go anyway, made testing easier and you had a defined dependency and initialisation order.

**Comment by an-tex** [comment]
Any update / thoughts? Having a kamon object (aka singleton *sigh*) again instead of doing it the proper DI way as before seems like quite a step back and it's unreliable as outlined before
